#!/bin/bash

export S2I_SOURCE_NOTEBOOK=${S2I_SOURCE_NOTEBOOK:-model.ipynb}
export S2I_MODEL_FILE=${S2I_MODEL_FILE:-model.pickle}
export S2I_MODEL_PATH=${S2I_MODEL_PATH:-/opt/sms/${S2I_MODEL_FILE}}

exec /opt/sms/app/bin/uwsgi --http 0.0.0.0:8080 --wsgi-file /opt/sms/app.py --callable app_dispatch
